routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;
use App\Varasalv;

Auth::routes();

Route::group(['middleware' => ['web','auth']], function(){
    Route::get('/', function () {
        return view('sissejuhatus/ajalugu');
    });

    Route::get('/sissejuhatus/ajalugu', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/ajalugu');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/ajalugu', $users);
        }
    });

    Route::get('/sissejuhatus/ristimine', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/ristimine');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/ristimine', $users);
        }
    });

    Route::get('/sissejuhatus/armulaud', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/armulaud');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/armulaud', $users);
        }
    });

    Route::get('/sissejuhatus/palve', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/palve');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/palve', $users);
        }
    });

    Route::get('/sissejuhatus/piibel', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/piibel');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/piibel', $users);
        }
    });

    Route::get('/sissejuhatus/10kasku', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/10kasku');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/10kasku', $users);
        }
    });

    Route::get('/sissejuhatus/usutunnistus', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/usutunnistus');
        } else {
            $users['users'] = \App\User::all();
            return view('adminsissejuhatus/usutunnistus', $users);
        }
    });

    Route::get('/kkk', function () {
        return view('kkk');
    });

    Route::get('/admin', function() {
        if (Auth::user()->admin == 0) {
            return view('sissejuhatus/ajalugu');
        } else {
            $users['users'] = \App\User::all();
            return view('admin', $users);
        }
    });


    Route::get('/varasalv', function () {
        return view('varasalv/varasalv');
    });

    Route::get('/varasalv/create', function () {
        return view('varasalv/create');
    });

    /* Varasalv middle pages */
    Route::get('varasalv/abielu', "Abielu@index");
    Route::get('varasalv/elujasurm', "Elujasurm@index");
    Route::get('varasalv/isiksus', "Isiksus@index");
    Route::get('varasalv/kirik', "Kirik@index");
    Route::get('varasalv/lastekasvatus', "Lastekasvatus@index");
    Route::get('varasalv/suhted', "Suhted@index");

    /* Varasalv individual pages */
    Route::resource('varasalvs', 'VarasalvController');

    /* Search function in Varasalv */
    Route::any('/search',function(){
        $q = Input::get ( 'q' );
        if($q != ""){
            $varasalv = Varasalv::where('pealkiri','LIKE','%'.$q.'%')
                                    ->orWhere('lyhikirjeldus','LIKE','%'.$q.'%')
                                    ->get();
            if(count($varasalv) > 0)
                return view('varasalv/search')->withDetails($varasalv)->withQuery($q);
        }
        return view('varasalv/search')->withMessage("Ei leidnud tulemusi...");
    });

    Route::get('/varasalv/search', function () {
        return view('varasalv/search');
    });

    //Route::get('/home', 'HomeController@home')->name('home');
    //Route::any('/varasalv/alfabeet', AlfabeetController@alfabeet)->name('alfabeet');
});

app/Varasalv.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Varasalv extends Model
{
    protected $fillable = ['kategooria', 'pealkiri', 'lyhikirjeldus', 'tekst'];
}

app/Http/Controllers/VarasalvController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Varasalv;

class VarasalvController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $varasalvs = Varasalv::all();
    
         return view('varasalv/index', compact('varasalvs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('varasalv/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
             'kategooria' => 'required|max:255',
             'pealkiri' => 'required|max:255',
             'lyhikirjeldus' => 'required|max:255',
             'tekst' => 'required|max:30000',
         ]);
         $varasalv = Varasalv::create($validatedData);

         
    
         return redirect('/varasalvs')->with('success', 'Õpetus on edukalt salvestatud');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $varasalv = Varasalv::findOrFail($id);
        return view('varasalv/show', compact('varasalv'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $varasalv = Varasalv::findOrFail($id);
    
        return view('varasalv/edit', compact('varasalv'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'kategooria' => 'required|max:255',
            'pealkiri' => 'required|max:255',
            'lyhikirjeldus' => 'required|max:255',
            'tekst' => 'required|max:30000',
        ]);
        Varasalv::whereId($id)->update($validatedData);

        return redirect('/varasalvs')->with('success', 'Õpetus on edukalt uuendatud');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $varasalv = Varasalv::findOrFail($id);
        $varasalv->delete();

        return redirect('/varasalvs')->with('success', 'Õpetus on edukalt kustutatud');
    }
}

resources/views/varasalv/abielu.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Abielu</h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/alfabeet.blade.php
@extends('layouts.app')

@section('content')

<div class="card-header">
    <div class="float-left"><h2>Tähestikuline õpetus...</h2></div>
    <div class="float-right">
        <a class="btn btn-success" href="{{ url('/varasalv') }}">
            <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
        </a>
    </div>
</div>

<div class="card-body">
    <div class="container-fluid">
    @if(isset($details))
            <p> Sinu tähe "<b> {{ $query }} </b>" kohta on järgmised teemad : </p>
            <table class="table table-stripped">
                <tbody>
                    @foreach($details as $varasalv)
                    <tr>
                        <td> <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$varasalv->id)}}">{{$varasalv->pealkiri}}</a> </td>
                        <td> {{ $varasalv->lyhikirjeldus}} </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @elseif(isset($message))
            <p>{{ $message}} </p>
        @endif
    </div>
</div>

@endsection

resources/views/varasalv/create.blade.php
<!-- create.blade.php -->

@extends('layouts.app')

@section('stylesheets')

  <style>
    .uper {
      margin-top: 40px;
    }
  </style>
@endsection

@section('content')

<div class="card uper">
  <div class="card-header">
    Lisa õpetus
    <div class="float-right">
        <a class="btn btn-success" href="{{ (url()->previous()) }}">
            <i class="fa fa-backspace"></i>{{ __('  Tagasi') }}
        </a>
    </div>
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('varasalvs.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Kategooria :</label>
              <input type="text" class="form-control" name="kategooria"/>
          </div>
          <div class="form-group">
              <label for="price">Pealkiri :</label>
              <input type="text" class="form-control" name="pealkiri"/>
          </div>
          <div class="form-group">
              <label for="quantity">Lühikirjeldus :</label>
              <input type="text" class="form-control" name="lyhikirjeldus"/>
          </div>
          <div class="form-group">
              <label for="quantity">Tekst :</label>
              <input id="mytextarea" type="textarea" class="form-control" name="tekst"/>
          </div>
          <button type="submit" class="btn btn-success">Loo õpetus</button>
      </form>
  </div>
</div>
@endsection

resources/views/varasalv/edit.blade.php
<!-- edit.blade.php -->

@extends('layouts.app')

@section('content')

<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Muuda õpetus
    <div class="float-right">
        <a class="btn btn-success" href="{{ url('/varasalvs') }}">
            <i class="fa fa-backspace"></i>{{ __('  Tagasi') }}
        </a>
    </div>
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('varasalvs.update', $varasalv->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Kategooria :</label>
              <input type="text" class="form-control" name="kategooria" value="{{$varasalv->kategooria}}"/>
          </div>
          <div class="form-group">
              <label for="price">Pealkiri :</label>
              <input type="text" class="form-control" name="pealkiri" value="{{$varasalv->pealkiri}}"/>
          </div>
          <div class="form-group">
              <label for="quantity">Lühikirjeldus :</label>
              <input type="text" class="form-control" name="lyhikirjeldus" value="{{$varasalv->lyhikirjeldus}}"/>
          </div>
          <div class="form-group">
              <label for="quantity">Tekst :</label>
              <input id="mytextarea" type="textarea" class="form-control" name="tekst" value="{{$varasalv->tekst}}"/>
          </div>
          <button type="submit" class="btn btn-success">Uuenda õpetus</button>
      </form>
  </div>
</div>
@endsection

resources/views/varasalv/elujasurm.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Elu ja surm<h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/index.blade.php
<!-- index.blade.php -->

@extends('layouts.app')

@section('content')

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <a class="btn btn-outline-success btn-block" href="{{ url('/varasalv/create') }}">
                {{ __('  Loo uus') }}</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Kategooria</td>
          <td>Pealkiri</td>
          <td>Lühikirjeldus</td>
          <td colspan="3">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($varasalvs as $varasalv)
        <tr>
            <td>{{$varasalv->id}}</td>
            <td>{{$varasalv->kategooria}}</td>
            <td>{{$varasalv->pealkiri}}</td>
            <td>{{$varasalv->lyhikirjeldus}}</td>
            <td><a href="{{ route('varasalvs.edit',$varasalv->id)}}" class="btn btn-primary">Muuda</a></td>
            <td><a href="{{ route('varasalvs.show',$varasalv->id)}}" class="btn btn-success">Vaata</a></td>
            <td>
                <form action="{{ route('varasalvs.destroy', $varasalv->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Kustuta</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
@endsection

resources/views/varasalv/isiksus.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Isiksus<h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/kirik.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Kirik<h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/lastekasvatus.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Lastekasvatus<h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/search.blade.php
@extends('layouts.app')

@section('content')

<div class="card-header">
    <div class="float-left"><h2>Otsi varasalvest...</h2></div>
    <div class="float-right">
        <a class="btn btn-success" href="{{ url('/varasalv') }}">
            <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
        </a>
    </div>
</div>

<div class="card-body">
    <div class="container-fluid">
        <!--Searchbar-->
        <form action="{{URL::to('/search')}}" method="POST" role="search">
            {{ csrf_field() }}
            <div class="input-group col-md-12">
                <input type="text" class="form-control" name="q" 
                    placeholder="Otsi..." ><span class="input-group-btn">
                    <button type="submit" class="btn btn-success" >
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>

        @if(isset($details))
            <p> Sinu otsingu "<b> {{ $query }} </b>" tulemused on : </p>
            <table class="table table-stripped">
                <tbody>
                    @foreach($details as $varasalv)
                    <tr>
                        <td> <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$varasalv->id)}}">{{$varasalv->pealkiri}}</a> </td>
                        <td> {{ $varasalv->lyhikirjeldus}} </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @elseif(isset($message))
            <p>{{ $message}} </p>
        @endif

    </div>
</div>

@endsection

resources/views/varasalv/show.blade.php
<!-- show.blade.php -->

@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    <div class="float-left"><h2>{{$varasalv->pealkiri}}</h2></div>
    <div class="float-right">
        <a class="btn btn-success" href="{{ (url()->previous()) }}">
            <i class="fa fa-backspace"></i>{{ __('  Tagasi') }}
        </a>
    </div>
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <div class="form-group">
        @csrf
        <p>{!! $varasalv->tekst !!}</p>
    </div>
</div>
@endsection

resources/views/varasalv/suhted.blade.php
@extends('layouts.app')

    @section('content')

        <div class="card-header">
            <div class="float-left"><h2>Suhted<h2></div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ url('/varasalv') }}">
                    <i class="fa fa-backspace"></i>{{ __('  Varasalv') }}
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="container-fluid">
                @foreach($data as $item)
                <div class="row top-buffer">
                    <div class="col-md-4 col-sm-6">
                        <a class="btn btn-success btn-block" href="{{ route('varasalvs.show',$item->id)}}">{{$item->pealkiri}}</a>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <p>{{$item->lyhikirjeldus}}</p>
                    </div>   
                </div>
                @endforeach
            </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-center">
            <span>{{$data->links()}}</span>
        </div>

    @endsection

resources/views/varasalv/varasalv.blade.php
@extends('layouts.app')

@section('content')

<div class="card-header">
    <div class="float-left"><h2>Varasalv</h2></div>
    <div class="float-right">
        <a class="btn btn-success float-right" href="{{ url('/varasalv/search') }}">
            <i class="fa fa-search"></i>{{ __('  Otsi Varasalvest...') }}
        </a>
    </div>
</div>

<div class="card-body">
    <div class="container-fluid">
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/abielu') }}">{{ __('Abielu') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Siia on koondatud kristliku abielu seletus ja nõuanded selle teekonna paremaks läbimiseks
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/lastekasvatus') }}">{{ __('Lastekasvatus') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Milline on kristlik lastekasvatus? Mida loeme Piiblist selle kohta?
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/elujasurm') }}">{{ __('Elu ja surm') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Inimese surelikkus ja selle maailma kaduvus. Kuidas toime tulla surmaga?
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/isiksus') }}">{{ __('Isiksus') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Materjalid, mis aitavad kristlasena kasvada
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/suhted') }}">{{ __('Suhted') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Kuidas saame paremini hoida suhteid lähedastega ja meid ümbritsevaga.
            </div>
        </div>
        <div class="row top-buffer">
            <div class="col-md-4 col-sm-6">
                <a class="btn btn-success btn-block" href="{{ url('/varasalv/kirik') }}">{{ __('Kirik') }}</a>
            </div>
            <div class="col-md-8 col-sm-6">
            Mina ja kogudus. Mida peaks kristlikkust kirikust teadma?
            </div>
        </div>

    <!--<div class="row top-buffer">
            <form action="{{URL::to('/varasalv/alfabeet')}}" method="POST" role="search">
                <a class="btn btn-success btn-sm" href="{{ url('/varasalv/alfabeet') }}" type="submit"  role="button" id="a">A</a>
                <a class="btn btn-success btn-sm" href="{{ url('/varasalv/alfabeet') }}" type="submit"  role="button" id="b">B</a>
                <a class="btn btn-success btn-sm" href="{{ url('/varasalv/alfabeet') }}" type="submit"  role="button" id="c">C</a>
                <a class="btn btn-success btn-sm" href="{{ url('/varasalv/alfabeet') }}" type="submit"  role="button" id="d">D</a>
                <a class="btn btn-success btn-sm" href="#" role="button">E</a>
                <a class="btn btn-success btn-sm" href="#" role="button">F</a>
                <a class="btn btn-success btn-sm" href="#" role="button">G</a>
                <a class="btn btn-success btn-sm" href="#" role="button">H</a>
                <a class="btn btn-success btn-sm" href="#" role="button">I</a>
                <a class="btn btn-success btn-sm" href="#" role="button">J</a>
                <a class="btn btn-success btn-sm" href="#" role="button">K</a>
                <a class="btn btn-success btn-sm" href="#" role="button">L</a>
                <a class="btn btn-success btn-sm" href="#" role="button">M</a>
                <a class="btn btn-success btn-sm" href="#" role="button">N</a>
                <a class="btn btn-success btn-sm" href="#" role="button">O</a>
                <a class="btn btn-success btn-sm" href="#" role="button">P</a>
                <a class="btn btn-success btn-sm" href="#" role="button">R</a>
                <a class="btn btn-success btn-sm" href="#" role="button">S</a>
                <a class="btn btn-success btn-sm" href="#" role="button">T</a>
                <a class="btn btn-success btn-sm" href="#" role="button">U</a>
                <a class="btn btn-success btn-sm" href="#" role="button">V</a>
                <a class="btn btn-success btn-sm" href="#" role="button">Õ</a>
                <a class="btn btn-success btn-sm" href="#" role="button">Ä</a>
                <a class="btn btn-success btn-sm" href="#" role="button">Ö</a>
                <a class="btn btn-success btn-sm" href="#" role="button">Ü</a>
            </form>
        </div>-->
    </div>
</div>

@endsection